<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Windows_Optimize_Harden_Debloat</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>sosavatar.ico</ApplicationIcon>
    <ApplicationManifest>Windows-Optimize-Harden-Debloat.exe.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <None Update="Read-ScriptOptions.ps1" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="sosavatar.ico" />
  </ItemGroup>

</Project>