name: VirusTotal Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan files
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./Windows-Optimize-Harden-Debloat.sln
            ./Windows-Optimize-Harden-Debloat.exe.manifest
            ./Windows-Optimize-Harden-Debloat.csproj
            ./Program.cs
            ./Form1.resx
            ./Form1.cs 
            ./Form1.Designer.cs
            ./App.config

      - name: Calculate SHA-256 Hashes
        run: find . -type f -print0 | xargs -0 sha256sum | awk '{print $1}'
